services:
  gateway:
    build: ./gateway
    ports:
      - "3010:3000" 
    environment:
      - SERVICE_A_URL=http://service-a:3001/work
      - SERVICE_B_URL=http://service-b:3001/work # Now points to 3001
    depends_on:
      - service-a
      - service-b
      - collector

  service-a:
    build: ./service-a
    ports:
      - "3001:3001"
    environment:
      - SERVICE_NAME=service-a
      - PORT=3001 
    depends_on:
      - collector

  service-b:
    build: ./service-b
    ports:
      - "3002:3001" # Host 3002 maps to Container 3001
    environment:
      - SERVICE_NAME=service-b
      - PORT=3001   # Internal port is now 3001
    depends_on:
      - collector

  collector:
    build: ./collector
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml